# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3'
services:
  # MySQL
  mysql:
    image: "mysql:latest"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ../init/mysql/conf.d:/etc/mysql/conf.d:ro
      - ../init/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
  # NATS
  nats:
    hostname: nats
    image: "nats:2.1.0"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"