// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifySignInParams struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifySignInParams) Reset()         { *m = VerifySignInParams{} }
func (m *VerifySignInParams) String() string { return proto.CompactTextString(m) }
func (*VerifySignInParams) ProtoMessage()    {}
func (*VerifySignInParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *VerifySignInParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifySignInParams.Unmarshal(m, b)
}
func (m *VerifySignInParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifySignInParams.Marshal(b, m, deterministic)
}
func (m *VerifySignInParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifySignInParams.Merge(m, src)
}
func (m *VerifySignInParams) XXX_Size() int {
	return xxx_messageInfo_VerifySignInParams.Size(m)
}
func (m *VerifySignInParams) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifySignInParams.DiscardUnknown(m)
}

var xxx_messageInfo_VerifySignInParams proto.InternalMessageInfo

func (m *VerifySignInParams) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifySignInParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// CreateUser:CreateUserParams
type CreateUserParams struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserParams) Reset()         { *m = CreateUserParams{} }
func (m *CreateUserParams) String() string { return proto.CompactTextString(m) }
func (*CreateUserParams) ProtoMessage()    {}
func (*CreateUserParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserParams.Unmarshal(m, b)
}
func (m *CreateUserParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserParams.Marshal(b, m, deterministic)
}
func (m *CreateUserParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserParams.Merge(m, src)
}
func (m *CreateUserParams) XXX_Size() int {
	return xxx_messageInfo_CreateUserParams.Size(m)
}
func (m *CreateUserParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserParams proto.InternalMessageInfo

func (m *CreateUserParams) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserParams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserParams) Reset()         { *m = GetUserParams{} }
func (m *GetUserParams) String() string { return proto.CompactTextString(m) }
func (*GetUserParams) ProtoMessage()    {}
func (*GetUserParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetUserParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserParams.Unmarshal(m, b)
}
func (m *GetUserParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserParams.Marshal(b, m, deterministic)
}
func (m *GetUserParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserParams.Merge(m, src)
}
func (m *GetUserParams) XXX_Size() int {
	return xxx_messageInfo_GetUserParams.Size(m)
}
func (m *GetUserParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserParams proto.InternalMessageInfo

type UpdatePasswordParams struct {
	CurrentPassword      string   `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordParams) Reset()         { *m = UpdatePasswordParams{} }
func (m *UpdatePasswordParams) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordParams) ProtoMessage()    {}
func (*UpdatePasswordParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UpdatePasswordParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordParams.Unmarshal(m, b)
}
func (m *UpdatePasswordParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordParams.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordParams.Merge(m, src)
}
func (m *UpdatePasswordParams) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordParams.Size(m)
}
func (m *UpdatePasswordParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordParams proto.InternalMessageInfo

func (m *UpdatePasswordParams) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *UpdatePasswordParams) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type UpdatePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordResponse) Reset()         { *m = UpdatePasswordResponse{} }
func (m *UpdatePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordResponse) ProtoMessage()    {}
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UpdatePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordResponse.Unmarshal(m, b)
}
func (m *UpdatePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordResponse.Merge(m, src)
}
func (m *UpdatePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordResponse.Size(m)
}
func (m *UpdatePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordResponse proto.InternalMessageInfo

type ForgotPasswordParams struct {
	Username             *wrappers.StringValue `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                *wrappers.StringValue `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Language             string                `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ForgotPasswordParams) Reset()         { *m = ForgotPasswordParams{} }
func (m *ForgotPasswordParams) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordParams) ProtoMessage()    {}
func (*ForgotPasswordParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *ForgotPasswordParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordParams.Unmarshal(m, b)
}
func (m *ForgotPasswordParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordParams.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordParams.Merge(m, src)
}
func (m *ForgotPasswordParams) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordParams.Size(m)
}
func (m *ForgotPasswordParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordParams.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordParams proto.InternalMessageInfo

func (m *ForgotPasswordParams) GetUsername() *wrappers.StringValue {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *ForgotPasswordParams) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *ForgotPasswordParams) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Roles                []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type ResetPasswordParams struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordParams) Reset()         { *m = ResetPasswordParams{} }
func (m *ResetPasswordParams) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordParams) ProtoMessage()    {}
func (*ResetPasswordParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *ResetPasswordParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordParams.Unmarshal(m, b)
}
func (m *ResetPasswordParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordParams.Marshal(b, m, deterministic)
}
func (m *ResetPasswordParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordParams.Merge(m, src)
}
func (m *ResetPasswordParams) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordParams.Size(m)
}
func (m *ResetPasswordParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordParams.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordParams proto.InternalMessageInfo

func (m *ResetPasswordParams) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ResetPasswordParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResetPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordResponse) Reset()         { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()    {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *ResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResponse.Unmarshal(m, b)
}
func (m *ResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResponse.Merge(m, src)
}
func (m *ResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResponse.Size(m)
}
func (m *ResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResponse proto.InternalMessageInfo

type VerifyPasswordParams struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordParams) Reset()         { *m = VerifyPasswordParams{} }
func (m *VerifyPasswordParams) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordParams) ProtoMessage()    {}
func (*VerifyPasswordParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *VerifyPasswordParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordParams.Unmarshal(m, b)
}
func (m *VerifyPasswordParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordParams.Marshal(b, m, deterministic)
}
func (m *VerifyPasswordParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordParams.Merge(m, src)
}
func (m *VerifyPasswordParams) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordParams.Size(m)
}
func (m *VerifyPasswordParams) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordParams.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordParams proto.InternalMessageInfo

func (m *VerifyPasswordParams) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordResponse) Reset()         { *m = VerifyPasswordResponse{} }
func (m *VerifyPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordResponse) ProtoMessage()    {}
func (*VerifyPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *VerifyPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordResponse.Unmarshal(m, b)
}
func (m *VerifyPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordResponse.Marshal(b, m, deterministic)
}
func (m *VerifyPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordResponse.Merge(m, src)
}
func (m *VerifyPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordResponse.Size(m)
}
func (m *VerifyPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*VerifySignInParams)(nil), "pepeunlimited.users.VerifySignInParams")
	proto.RegisterType((*CreateUserParams)(nil), "pepeunlimited.users.CreateUserParams")
	proto.RegisterType((*GetUserParams)(nil), "pepeunlimited.users.GetUserParams")
	proto.RegisterType((*UpdatePasswordParams)(nil), "pepeunlimited.users.UpdatePasswordParams")
	proto.RegisterType((*UpdatePasswordResponse)(nil), "pepeunlimited.users.UpdatePasswordResponse")
	proto.RegisterType((*ForgotPasswordParams)(nil), "pepeunlimited.users.ForgotPasswordParams")
	proto.RegisterType((*User)(nil), "pepeunlimited.users.User")
	proto.RegisterType((*ResetPasswordParams)(nil), "pepeunlimited.users.ResetPasswordParams")
	proto.RegisterType((*ResetPasswordResponse)(nil), "pepeunlimited.users.ResetPasswordResponse")
	proto.RegisterType((*VerifyPasswordParams)(nil), "pepeunlimited.users.VerifyPasswordParams")
	proto.RegisterType((*VerifyPasswordResponse)(nil), "pepeunlimited.users.VerifyPasswordResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0xdb, 0x95, 0x8f, 0xdb, 0xad, 0x9b, 0xdc, 0x32, 0x4a, 0x40, 0x68, 0x44, 0x42, 0x6c,
	0x80, 0x32, 0xa9, 0xbc, 0xf0, 0x0c, 0x82, 0x81, 0x84, 0xd0, 0x94, 0x6a, 0x7b, 0xe0, 0x81, 0xe1,
	0x35, 0x77, 0x21, 0x22, 0xb1, 0x2d, 0xdb, 0xa1, 0xda, 0xbf, 0xe0, 0x27, 0xf0, 0x53, 0x91, 0xe3,
	0x24, 0x6b, 0x82, 0x5b, 0x2a, 0xf1, 0x78, 0x7d, 0x3f, 0x4e, 0xee, 0x39, 0x27, 0x17, 0x20, 0x57,
	0x28, 0x03, 0x21, 0xb9, 0xe6, 0x64, 0x24, 0x50, 0x60, 0xce, 0xd2, 0x24, 0x4b, 0x34, 0x46, 0x81,
	0xc9, 0x28, 0xef, 0x61, 0xcc, 0x79, 0x9c, 0xe2, 0x71, 0x51, 0x72, 0x99, 0x5f, 0x1d, 0x63, 0x26,
	0xf4, 0xb5, 0xed, 0xf0, 0x1e, 0xb7, 0x93, 0x0b, 0x49, 0x85, 0x40, 0xa9, 0x6c, 0xde, 0xff, 0x04,
	0xe4, 0x1c, 0x65, 0x72, 0x75, 0x3d, 0x4b, 0x62, 0xf6, 0x91, 0x9d, 0x52, 0x49, 0x33, 0x45, 0x3c,
	0xb8, 0x63, 0x66, 0x33, 0x9a, 0xe1, 0xa4, 0x73, 0xd0, 0x39, 0xbc, 0x1b, 0xd6, 0xb1, 0xc9, 0x09,
	0xaa, 0xd4, 0x82, 0xcb, 0x68, 0xd2, 0xb5, 0xb9, 0x2a, 0xf6, 0xbf, 0xc1, 0xde, 0x5b, 0x89, 0x54,
	0xe3, 0x99, 0x42, 0xf9, 0x7f, 0xb3, 0xc8, 0x18, 0xfa, 0x98, 0xd1, 0x24, 0x9d, 0xf4, 0x8a, 0x84,
	0x0d, 0xfc, 0x5d, 0xd8, 0x39, 0x41, 0x7d, 0x33, 0xde, 0x8f, 0x60, 0x7c, 0x26, 0x22, 0xaa, 0xf1,
	0xb4, 0x6c, 0x2c, 0x61, 0x8f, 0x60, 0x6f, 0x9e, 0x4b, 0x89, 0x4c, 0x5f, 0xd4, 0x10, 0x16, 0x7e,
	0xb7, 0x7c, 0xaf, 0x1a, 0xc8, 0x13, 0xd8, 0x66, 0xb8, 0xb8, 0x68, 0x7d, 0xc9, 0x80, 0xe1, 0xa2,
	0x2a, 0xf1, 0x27, 0xb0, 0xdf, 0x44, 0x09, 0x51, 0x09, 0xce, 0x14, 0xfa, 0xbf, 0x3b, 0x30, 0x7e,
	0xcf, 0x65, 0xcc, 0x75, 0xeb, 0x03, 0x5e, 0xb7, 0xf6, 0x1e, 0x4c, 0x1f, 0x05, 0x56, 0x8c, 0xa0,
	0x12, 0x23, 0x98, 0x69, 0x99, 0xb0, 0xf8, 0x9c, 0xa6, 0x39, 0x2e, 0xb1, 0x32, 0xad, 0x36, 0xef,
	0x6e, 0xd0, 0x66, 0x4b, 0x0d, 0x93, 0x29, 0x65, 0x71, 0x4e, 0x63, 0x2c, 0x09, 0xab, 0x63, 0xff,
	0x2b, 0x6c, 0x19, 0xc2, 0xc8, 0x10, 0xba, 0x89, 0x25, 0xa1, 0x17, 0x76, 0x93, 0xa8, 0xa1, 0x4c,
	0xb7, 0xa5, 0x8c, 0x93, 0x7d, 0xf3, 0x2a, 0x79, 0x8a, 0x6a, 0xb2, 0x75, 0xd0, 0x33, 0xaf, 0x45,
	0xe0, 0x9f, 0xc0, 0x28, 0x44, 0x85, 0x6d, 0x02, 0xc6, 0xd0, 0xd7, 0xfc, 0x07, 0xb2, 0x92, 0x76,
	0x1b, 0xac, 0xb5, 0xcf, 0x7d, 0xb8, 0xd7, 0x18, 0x54, 0x93, 0xfc, 0x12, 0xc6, 0xd6, 0xa5, 0x9b,
	0x40, 0x18, 0xb1, 0x9a, 0xd5, 0xd5, 0x9c, 0xe9, 0xaf, 0x3e, 0x0c, 0x0c, 0x15, 0x33, 0x94, 0x3f,
	0x93, 0x39, 0x92, 0xcf, 0x00, 0x37, 0x7e, 0x25, 0x4f, 0x03, 0xc7, 0xef, 0x15, 0xb4, 0x0d, 0xed,
	0x3d, 0x70, 0x96, 0x15, 0x13, 0xbe, 0xc3, 0xb0, 0x69, 0x13, 0x72, 0xe4, 0x2e, 0x76, 0x38, 0xd6,
	0x7b, 0xb1, 0x41, 0x69, 0xb5, 0x09, 0x99, 0xc1, 0xb0, 0xe9, 0xba, 0x15, 0x48, 0x2e, 0x6b, 0x7a,
	0xfb, 0x7f, 0x39, 0xea, 0x9d, 0x39, 0x19, 0x24, 0x83, 0x91, 0x25, 0xae, 0xa1, 0xc2, 0x8a, 0xc9,
	0x2e, 0x41, 0x56, 0xec, 0xe0, 0x56, 0x83, 0x20, 0xec, 0x34, 0x81, 0x0e, 0x9d, 0xdd, 0x0e, 0x6f,
	0x79, 0xcf, 0xff, 0x5d, 0x59, 0xc3, 0x7c, 0x80, 0xdb, 0xe5, 0xc9, 0x20, 0xbe, 0xb3, 0xad, 0x71,
	0x50, 0xd6, 0xc9, 0x1b, 0xc2, 0xf6, 0xf2, 0xb1, 0x24, 0xcf, 0xd6, 0x6c, 0xbb, 0x7c, 0x4f, 0xd7,
	0xcc, 0x7c, 0xd3, 0xff, 0xd2, 0x93, 0x62, 0x7e, 0x79, 0xab, 0x90, 0xe2, 0xd5, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x1d, 0x1d, 0xa7, 0x63, 0xee, 0x05, 0x00, 0x00,
}
