// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package usersrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetProfilePictureParams struct {
	ProfilePictureId     int64    `protobuf:"varint,1,opt,name=profile_picture_id,json=profilePictureId,proto3" json:"profile_picture_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetProfilePictureParams) Reset()         { *m = SetProfilePictureParams{} }
func (m *SetProfilePictureParams) String() string { return proto.CompactTextString(m) }
func (*SetProfilePictureParams) ProtoMessage()    {}
func (*SetProfilePictureParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *SetProfilePictureParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProfilePictureParams.Unmarshal(m, b)
}
func (m *SetProfilePictureParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProfilePictureParams.Marshal(b, m, deterministic)
}
func (m *SetProfilePictureParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProfilePictureParams.Merge(m, src)
}
func (m *SetProfilePictureParams) XXX_Size() int {
	return xxx_messageInfo_SetProfilePictureParams.Size(m)
}
func (m *SetProfilePictureParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProfilePictureParams.DiscardUnknown(m)
}

var xxx_messageInfo_SetProfilePictureParams proto.InternalMessageInfo

func (m *SetProfilePictureParams) GetProfilePictureId() int64 {
	if m != nil {
		return m.ProfilePictureId
	}
	return 0
}

func (m *SetProfilePictureParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DeleteProfilePictureParams struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProfilePictureParams) Reset()         { *m = DeleteProfilePictureParams{} }
func (m *DeleteProfilePictureParams) String() string { return proto.CompactTextString(m) }
func (*DeleteProfilePictureParams) ProtoMessage()    {}
func (*DeleteProfilePictureParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *DeleteProfilePictureParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProfilePictureParams.Unmarshal(m, b)
}
func (m *DeleteProfilePictureParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProfilePictureParams.Marshal(b, m, deterministic)
}
func (m *DeleteProfilePictureParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProfilePictureParams.Merge(m, src)
}
func (m *DeleteProfilePictureParams) XXX_Size() int {
	return xxx_messageInfo_DeleteProfilePictureParams.Size(m)
}
func (m *DeleteProfilePictureParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProfilePictureParams.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProfilePictureParams proto.InternalMessageInfo

func (m *DeleteProfilePictureParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ProfilePicture struct {
	ProfilePictureId     int64    `protobuf:"varint,1,opt,name=profile_picture_id,json=profilePictureId,proto3" json:"profile_picture_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfilePicture) Reset()         { *m = ProfilePicture{} }
func (m *ProfilePicture) String() string { return proto.CompactTextString(m) }
func (*ProfilePicture) ProtoMessage()    {}
func (*ProfilePicture) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *ProfilePicture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilePicture.Unmarshal(m, b)
}
func (m *ProfilePicture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilePicture.Marshal(b, m, deterministic)
}
func (m *ProfilePicture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilePicture.Merge(m, src)
}
func (m *ProfilePicture) XXX_Size() int {
	return xxx_messageInfo_ProfilePicture.Size(m)
}
func (m *ProfilePicture) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilePicture.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilePicture proto.InternalMessageInfo

func (m *ProfilePicture) GetProfilePictureId() int64 {
	if m != nil {
		return m.ProfilePictureId
	}
	return 0
}

// CreateUser:CreateUserParams
type CreateUserParams struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserParams) Reset()         { *m = CreateUserParams{} }
func (m *CreateUserParams) String() string { return proto.CompactTextString(m) }
func (*CreateUserParams) ProtoMessage()    {}
func (*CreateUserParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *CreateUserParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserParams.Unmarshal(m, b)
}
func (m *CreateUserParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserParams.Marshal(b, m, deterministic)
}
func (m *CreateUserParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserParams.Merge(m, src)
}
func (m *CreateUserParams) XXX_Size() int {
	return xxx_messageInfo_CreateUserParams.Size(m)
}
func (m *CreateUserParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserParams proto.InternalMessageInfo

func (m *CreateUserParams) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserParams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Roles                []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	ProfilePictureId     int64    `protobuf:"varint,5,opt,name=profile_picture_id,json=profilePictureId,proto3" json:"profile_picture_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *User) GetProfilePictureId() int64 {
	if m != nil {
		return m.ProfilePictureId
	}
	return 0
}

type GetUserParams struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserParams) Reset()         { *m = GetUserParams{} }
func (m *GetUserParams) String() string { return proto.CompactTextString(m) }
func (*GetUserParams) ProtoMessage()    {}
func (*GetUserParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *GetUserParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserParams.Unmarshal(m, b)
}
func (m *GetUserParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserParams.Marshal(b, m, deterministic)
}
func (m *GetUserParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserParams.Merge(m, src)
}
func (m *GetUserParams) XXX_Size() int {
	return xxx_messageInfo_GetUserParams.Size(m)
}
func (m *GetUserParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserParams proto.InternalMessageInfo

func (m *GetUserParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*SetProfilePictureParams)(nil), "pepeunlimited.users.SetProfilePictureParams")
	proto.RegisterType((*DeleteProfilePictureParams)(nil), "pepeunlimited.users.DeleteProfilePictureParams")
	proto.RegisterType((*ProfilePicture)(nil), "pepeunlimited.users.ProfilePicture")
	proto.RegisterType((*CreateUserParams)(nil), "pepeunlimited.users.CreateUserParams")
	proto.RegisterType((*User)(nil), "pepeunlimited.users.User")
	proto.RegisterType((*GetUserParams)(nil), "pepeunlimited.users.GetUserParams")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcb, 0x4a, 0xf3, 0x40,
	0x14, 0x26, 0xe9, 0xfd, 0xfc, 0xfc, 0xa5, 0x8e, 0x85, 0xd6, 0x08, 0x52, 0x22, 0x42, 0x17, 0x25,
	0x05, 0xc5, 0xad, 0x0b, 0x15, 0xb4, 0x1b, 0x29, 0x2d, 0x6e, 0xdc, 0xb4, 0x69, 0x73, 0x5a, 0x06,
	0x92, 0x66, 0x98, 0x99, 0x58, 0x7c, 0x07, 0x5f, 0x59, 0x90, 0x99, 0x94, 0xda, 0xc4, 0x89, 0xe8,
	0xf2, 0xcc, 0x77, 0x39, 0x17, 0xbe, 0x01, 0x48, 0x04, 0x72, 0x8f, 0xf1, 0x58, 0xc6, 0xe4, 0x98,
	0x21, 0xc3, 0x64, 0x13, 0xd2, 0x88, 0x4a, 0x0c, 0x3c, 0x85, 0x08, 0xe7, 0x74, 0x1d, 0xc7, 0xeb,
	0x10, 0x87, 0x9a, 0xb2, 0x48, 0x56, 0x43, 0x8c, 0x98, 0x7c, 0x4b, 0x15, 0xce, 0x59, 0x1e, 0xdc,
	0x72, 0x9f, 0x31, 0xe4, 0x22, 0xc5, 0xdd, 0x39, 0x74, 0xa6, 0x28, 0xc7, 0x3c, 0x5e, 0xd1, 0x10,
	0xc7, 0x74, 0x29, 0x13, 0x8e, 0x63, 0x9f, 0xfb, 0x91, 0x20, 0x03, 0x20, 0x2c, 0x7d, 0x9f, 0xb1,
	0x14, 0x98, 0xd1, 0xa0, 0x6b, 0xf5, 0xac, 0x7e, 0x69, 0xd2, 0x62, 0x19, 0xc5, 0x28, 0x20, 0x1d,
	0xa8, 0xa9, 0x71, 0x14, 0xc5, 0xd6, 0x94, 0xaa, 0x2a, 0x47, 0x81, 0x7b, 0x0d, 0xce, 0x3d, 0x86,
	0x28, 0xd1, 0xd8, 0xe4, 0x40, 0x66, 0x65, 0x64, 0x37, 0xd0, 0xcc, 0x0a, 0xfe, 0x36, 0x8f, 0x3b,
	0x87, 0xd6, 0x1d, 0x47, 0x5f, 0xe2, 0xb3, 0x40, 0xbe, 0x6b, 0xe6, 0x40, 0x5d, 0xb9, 0x6f, 0xfc,
	0x08, 0xb5, 0xae, 0x31, 0xd9, 0xd7, 0x0a, 0x63, 0xbe, 0x10, 0xdb, 0x98, 0xa7, 0x0b, 0x34, 0x26,
	0xfb, 0x9a, 0xb4, 0xa1, 0x82, 0x91, 0x4f, 0xc3, 0x6e, 0x49, 0x03, 0x69, 0xe1, 0xbe, 0x5b, 0x50,
	0x56, 0xe6, 0xa4, 0x09, 0xf6, 0x7e, 0x10, 0x9b, 0x06, 0x99, 0x36, 0x76, 0xae, 0x8d, 0xd1, 0x4a,
	0xbd, 0xf2, 0x38, 0x44, 0xd1, 0x2d, 0xf7, 0x4a, 0xea, 0x55, 0x17, 0x05, 0x0b, 0x57, 0x0a, 0x16,
	0xee, 0xc3, 0xff, 0x07, 0x94, 0x07, 0xdb, 0x16, 0x9d, 0xf6, 0xf2, 0xc3, 0x86, 0x7f, 0x8a, 0x37,
	0x45, 0xfe, 0x4a, 0x97, 0x48, 0x9e, 0x00, 0xbe, 0x4e, 0x45, 0x2e, 0x3c, 0x43, 0xc8, 0xbc, 0xfc,
	0x2d, 0x9d, 0x13, 0x23, 0x4d, 0x3b, 0x3c, 0x42, 0x6d, 0x37, 0x09, 0x71, 0x8d, 0xac, 0xcc, 0x9c,
	0x3f, 0x39, 0xad, 0xe0, 0xe8, 0x5b, 0x3a, 0xc9, 0xc0, 0xc8, 0x2f, 0x48, 0xb1, 0x73, 0x6e, 0x64,
	0xe7, 0x2c, 0x43, 0x68, 0x9b, 0x32, 0x4a, 0x86, 0x46, 0x71, 0x71, 0x9c, 0x7f, 0xd5, 0xed, 0x16,
	0x5e, 0xea, 0x9c, 0x2d, 0x35, 0xb4, 0xa8, 0xea, 0x6f, 0x78, 0xf5, 0x19, 0x00, 0x00, 0xff, 0xff,
	0xbd, 0xf0, 0x0c, 0x38, 0xe6, 0x03, 0x00, 0x00,
}
