// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	predicate2 "github.com/pepeunlimited/users/internal/app/app1/ent/predicate"
	ticket2 "github.com/pepeunlimited/users/internal/app/app1/ent/ticket"

	"github.com/facebookincubator/ent/dialect/sql"
)

// TicketDelete is the builder for deleting a Ticket entity.
type TicketDelete struct {
	config
	predicates []predicate2.Ticket
}

// Where adds a new predicate to the delete builder.
func (td *TicketDelete) Where(ps ...predicate2.Ticket) *TicketDelete {
	td.predicates = append(td.predicates, ps...)
	return td
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (td *TicketDelete) Exec(ctx context.Context) (int, error) {
	return td.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (td *TicketDelete) ExecX(ctx context.Context) int {
	n, err := td.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (td *TicketDelete) sqlExec(ctx context.Context) (int, error) {
	var (
		res     sql.Result
		builder = sql.Dialect(td.driver.Dialect())
	)
	selector := builder.Select().From(sql.Table(ticket2.Table))
	for _, p := range td.predicates {
		p(selector)
	}
	query, args := builder.Delete(ticket2.Table).FromSelect(selector).Query()
	if err := td.driver.Exec(ctx, query, args, &res); err != nil {
		return 0, err
	}
	affected, err := res.RowsAffected()
	if err != nil {
		return 0, err
	}
	return int(affected), nil
}

// TicketDeleteOne is the builder for deleting a single Ticket entity.
type TicketDeleteOne struct {
	td *TicketDelete
}

// Exec executes the deletion query.
func (tdo *TicketDeleteOne) Exec(ctx context.Context) error {
	n, err := tdo.td.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &ErrNotFound{ticket2.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tdo *TicketDeleteOne) ExecX(ctx context.Context) {
	tdo.td.ExecX(ctx)
}
