// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
