// Code generated by protoc-gen-go. DO NOT EDIT.
// source: credentials.proto

package rpccredentials

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifySignInParams struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifySignInParams) Reset()         { *m = VerifySignInParams{} }
func (m *VerifySignInParams) String() string { return proto.CompactTextString(m) }
func (*VerifySignInParams) ProtoMessage()    {}
func (*VerifySignInParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f10b41ff9e8e07a, []int{0}
}

func (m *VerifySignInParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifySignInParams.Unmarshal(m, b)
}
func (m *VerifySignInParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifySignInParams.Marshal(b, m, deterministic)
}
func (m *VerifySignInParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifySignInParams.Merge(m, src)
}
func (m *VerifySignInParams) XXX_Size() int {
	return xxx_messageInfo_VerifySignInParams.Size(m)
}
func (m *VerifySignInParams) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifySignInParams.DiscardUnknown(m)
}

var xxx_messageInfo_VerifySignInParams proto.InternalMessageInfo

func (m *VerifySignInParams) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifySignInParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdatePasswordParams struct {
	CurrentPassword      string   `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordParams) Reset()         { *m = UpdatePasswordParams{} }
func (m *UpdatePasswordParams) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordParams) ProtoMessage()    {}
func (*UpdatePasswordParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f10b41ff9e8e07a, []int{1}
}

func (m *UpdatePasswordParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordParams.Unmarshal(m, b)
}
func (m *UpdatePasswordParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordParams.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordParams.Merge(m, src)
}
func (m *UpdatePasswordParams) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordParams.Size(m)
}
func (m *UpdatePasswordParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordParams proto.InternalMessageInfo

func (m *UpdatePasswordParams) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *UpdatePasswordParams) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ForgotPasswordParams struct {
	Username             *wrappers.StringValue `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                *wrappers.StringValue `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Language             string                `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ForgotPasswordParams) Reset()         { *m = ForgotPasswordParams{} }
func (m *ForgotPasswordParams) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordParams) ProtoMessage()    {}
func (*ForgotPasswordParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f10b41ff9e8e07a, []int{2}
}

func (m *ForgotPasswordParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordParams.Unmarshal(m, b)
}
func (m *ForgotPasswordParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordParams.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordParams.Merge(m, src)
}
func (m *ForgotPasswordParams) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordParams.Size(m)
}
func (m *ForgotPasswordParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordParams.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordParams proto.InternalMessageInfo

func (m *ForgotPasswordParams) GetUsername() *wrappers.StringValue {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *ForgotPasswordParams) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *ForgotPasswordParams) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type ResetPasswordParams struct {
	TicketToken          string   `protobuf:"bytes,1,opt,name=ticket_token,json=ticketToken,proto3" json:"ticket_token,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordParams) Reset()         { *m = ResetPasswordParams{} }
func (m *ResetPasswordParams) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordParams) ProtoMessage()    {}
func (*ResetPasswordParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f10b41ff9e8e07a, []int{3}
}

func (m *ResetPasswordParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordParams.Unmarshal(m, b)
}
func (m *ResetPasswordParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordParams.Marshal(b, m, deterministic)
}
func (m *ResetPasswordParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordParams.Merge(m, src)
}
func (m *ResetPasswordParams) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordParams.Size(m)
}
func (m *ResetPasswordParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordParams.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordParams proto.InternalMessageInfo

func (m *ResetPasswordParams) GetTicketToken() string {
	if m != nil {
		return m.TicketToken
	}
	return ""
}

func (m *ResetPasswordParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type VerifyPasswordParams struct {
	TicketToken          string   `protobuf:"bytes,1,opt,name=ticket_token,json=ticketToken,proto3" json:"ticket_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordParams) Reset()         { *m = VerifyPasswordParams{} }
func (m *VerifyPasswordParams) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordParams) ProtoMessage()    {}
func (*VerifyPasswordParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f10b41ff9e8e07a, []int{4}
}

func (m *VerifyPasswordParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordParams.Unmarshal(m, b)
}
func (m *VerifyPasswordParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordParams.Marshal(b, m, deterministic)
}
func (m *VerifyPasswordParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordParams.Merge(m, src)
}
func (m *VerifyPasswordParams) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordParams.Size(m)
}
func (m *VerifyPasswordParams) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordParams.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordParams proto.InternalMessageInfo

func (m *VerifyPasswordParams) GetTicketToken() string {
	if m != nil {
		return m.TicketToken
	}
	return ""
}

type VerifySignInResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Roles                []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifySignInResponse) Reset()         { *m = VerifySignInResponse{} }
func (m *VerifySignInResponse) String() string { return proto.CompactTextString(m) }
func (*VerifySignInResponse) ProtoMessage()    {}
func (*VerifySignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f10b41ff9e8e07a, []int{5}
}

func (m *VerifySignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifySignInResponse.Unmarshal(m, b)
}
func (m *VerifySignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifySignInResponse.Marshal(b, m, deterministic)
}
func (m *VerifySignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifySignInResponse.Merge(m, src)
}
func (m *VerifySignInResponse) XXX_Size() int {
	return xxx_messageInfo_VerifySignInResponse.Size(m)
}
func (m *VerifySignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifySignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifySignInResponse proto.InternalMessageInfo

func (m *VerifySignInResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VerifySignInResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifySignInResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifySignInResponse) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterType((*VerifySignInParams)(nil), "pepeunlimited.users.VerifySignInParams")
	proto.RegisterType((*UpdatePasswordParams)(nil), "pepeunlimited.users.UpdatePasswordParams")
	proto.RegisterType((*ForgotPasswordParams)(nil), "pepeunlimited.users.ForgotPasswordParams")
	proto.RegisterType((*ResetPasswordParams)(nil), "pepeunlimited.users.ResetPasswordParams")
	proto.RegisterType((*VerifyPasswordParams)(nil), "pepeunlimited.users.VerifyPasswordParams")
	proto.RegisterType((*VerifySignInResponse)(nil), "pepeunlimited.users.VerifySignInResponse")
}

func init() { proto.RegisterFile("credentials.proto", fileDescriptor_9f10b41ff9e8e07a) }

var fileDescriptor_9f10b41ff9e8e07a = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x55, 0x12, 0x8a, 0x60, 0x12, 0x42, 0xd9, 0x58, 0x28, 0x32, 0x08, 0xb5, 0xbe, 0xd0, 0x5c,
	0x5c, 0x29, 0x5c, 0xe0, 0x0a, 0x02, 0x09, 0x89, 0x43, 0x49, 0x4a, 0x85, 0xb8, 0x44, 0x1b, 0x7b,
	0x6a, 0xad, 0x6a, 0xef, 0xae, 0x76, 0xd7, 0x58, 0xfd, 0x1b, 0xfe, 0x88, 0x5f, 0x42, 0xf6, 0x7a,
	0x8b, 0x6d, 0xec, 0x46, 0x1c, 0x67, 0x76, 0xe6, 0xcd, 0xcc, 0x7b, 0xcf, 0x86, 0x67, 0x91, 0xc2,
	0x18, 0xb9, 0x61, 0x34, 0xd5, 0xa1, 0x54, 0xc2, 0x08, 0xb2, 0x90, 0x28, 0x31, 0xe7, 0x29, 0xcb,
	0x98, 0xc1, 0x38, 0xcc, 0x35, 0x2a, 0xed, 0xbf, 0x48, 0x84, 0x48, 0x52, 0x3c, 0xaf, 0x4a, 0xf6,
	0xf9, 0xf5, 0x39, 0x66, 0xd2, 0xdc, 0xda, 0x0e, 0xff, 0x55, 0xf7, 0xb1, 0x50, 0x54, 0x4a, 0x54,
	0x35, 0x62, 0xf0, 0x05, 0xc8, 0x15, 0x2a, 0x76, 0x7d, 0xbb, 0x65, 0x09, 0xff, 0xcc, 0x2f, 0xa8,
	0xa2, 0x99, 0x26, 0x3e, 0x3c, 0x2a, 0xb1, 0x39, 0xcd, 0x70, 0x39, 0x3a, 0x19, 0x9d, 0x3d, 0xde,
	0xdc, 0xc5, 0xe5, 0x9b, 0xa4, 0x5a, 0x17, 0x42, 0xc5, 0xcb, 0xb1, 0x7d, 0x73, 0x71, 0x10, 0x83,
	0xf7, 0x4d, 0xc6, 0xd4, 0xe0, 0x45, 0x9d, 0xa9, 0xf1, 0x56, 0x70, 0x1c, 0xe5, 0x4a, 0x21, 0x37,
	0xbb, 0xbb, 0x5e, 0x8b, 0xfb, 0xb4, 0xce, 0xbb, 0x06, 0x72, 0x0a, 0x33, 0x8e, 0xc5, 0xae, 0x33,
	0x62, 0xca, 0xb1, 0x70, 0x25, 0xc1, 0xaf, 0x11, 0x78, 0x9f, 0x84, 0x4a, 0x84, 0xe9, 0x8c, 0x79,
	0xdb, 0x59, 0x7b, 0xba, 0x7e, 0x19, 0xda, 0xfb, 0x43, 0x77, 0x7f, 0xb8, 0x35, 0x8a, 0xf1, 0xe4,
	0x8a, 0xa6, 0x39, 0x36, 0x8e, 0x5a, 0xc3, 0x11, 0x66, 0x94, 0xa5, 0xd5, 0xb8, 0x43, 0x6d, 0xb6,
	0xb4, 0x24, 0x22, 0xa5, 0x3c, 0xc9, 0x69, 0x82, 0xcb, 0x89, 0x25, 0xc2, 0xc5, 0xc1, 0x25, 0x2c,
	0x36, 0xa8, 0xb1, 0xbb, 0xe0, 0x29, 0xcc, 0x0c, 0x8b, 0x6e, 0xd0, 0xec, 0x8c, 0xb8, 0x41, 0x5e,
	0x73, 0x30, 0xb5, 0xb9, 0xcb, 0x32, 0x75, 0x2f, 0xbd, 0xef, 0xc0, 0xb3, 0x62, 0xfd, 0x37, 0x6c,
	0xc0, 0x5d, 0xab, 0xd5, 0x79, 0x83, 0x5a, 0x0a, 0xae, 0x91, 0xcc, 0x61, 0xcc, 0xac, 0x16, 0x93,
	0xcd, 0x98, 0xc5, 0x2d, 0xe5, 0xc7, 0x1d, 0xe5, 0x3d, 0x47, 0x92, 0xbd, 0xb6, 0xa6, 0xc1, 0x83,
	0x23, 0x25, 0x52, 0xd4, 0xcb, 0x07, 0x27, 0x93, 0x32, 0x5b, 0x05, 0xeb, 0xdf, 0x13, 0x20, 0x1f,
	0xfe, 0xfa, 0x77, 0x8b, 0xea, 0x27, 0x8b, 0x90, 0x6c, 0x61, 0xde, 0x36, 0x08, 0x59, 0x85, 0x3d,
	0x9e, 0x0e, 0xfb, 0x5c, 0xe4, 0x3f, 0xff, 0x47, 0x95, 0x8f, 0xa5, 0xd3, 0x4b, 0xd0, 0xb6, 0x1d,
	0x06, 0x40, 0xfb, 0x3c, 0x33, 0x08, 0xfa, 0x1d, 0x16, 0x96, 0xb0, 0x96, 0x8e, 0x03, 0xc8, 0x7d,
	0xaa, 0x0c, 0x22, 0x7f, 0x85, 0x27, 0x6d, 0xcc, 0xb3, 0x5e, 0xcc, 0x1e, 0xff, 0x0c, 0x42, 0xee,
	0x61, 0xd6, 0x54, 0x97, 0xbc, 0xbe, 0x67, 0xcb, 0xe6, 0x87, 0xee, 0xaf, 0x0e, 0x16, 0x3a, 0xa7,
	0xbc, 0x3f, 0xfe, 0x31, 0x57, 0x32, 0x6a, 0xfc, 0x93, 0xf6, 0x0f, 0xab, 0x2d, 0xde, 0xfc, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xc9, 0x9a, 0xe6, 0xb8, 0xa9, 0x04, 0x00, 0x00,
}
